### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by heyarn01d** [DavidCico/Univariate-time-series-analysis-of-cryptocurrency-data-with-ARIMA-and-SARIMA-and-hypergrid-search#1]
Hi David,

Please could you upload the dataset in csv format?  for the Arima & Sarima crypto tutorial you wrote?   Thanks

**Comment by DavidCico** [comment]
Hi heyarn01d,

sorry I just saw your question now. Might be late but I have uploaded the dataset. Sorry for the inconvenience.

Cheers,

David

**Comment by heyarn01d** [comment]
Thanks David much appreciated.
